-- NovaIT Supabase Setup Script
-- Run this in Supabase Dashboard -> SQL Editor
-- Creates tables + RLS policies for admin panel & WhatsApp click tracking

-- =============================================
-- 1. WHATSAPP CLICKS TABLE
-- =============================================

CREATE TABLE IF NOT EXISTS public.whatsapp_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product text NOT NULL DEFAULT 'general',
  ip text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.whatsapp_clicks ENABLE ROW LEVEL SECURITY;

-- anyone can insert a click (anon users are visitors clicking WhatsApp buttons)
DROP POLICY IF EXISTS whatsapp_clicks_insert_anon ON public.whatsapp_clicks;
CREATE POLICY whatsapp_clicks_insert_anon
  ON public.whatsapp_clicks
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- only the admin can read clicks
DROP POLICY IF EXISTS whatsapp_clicks_admin_read ON public.whatsapp_clicks;
CREATE POLICY whatsapp_clicks_admin_read
  ON public.whatsapp_clicks
  FOR SELECT
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'prajwalnewpane775@gmail.com');

-- =============================================
-- 2. ADMIN: READ newsletter subscribers
-- =============================================

DROP POLICY IF EXISTS newsletter_admin_read ON public.newsletter;
CREATE POLICY newsletter_admin_read
  ON public.newsletter
  FOR SELECT
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'prajwalnewpane775@gmail.com');

-- =============================================
-- 3. ADMIN: READ all messages
-- =============================================

DROP POLICY IF EXISTS messages_admin_read ON public.messages;
CREATE POLICY messages_admin_read
  ON public.messages
  FOR SELECT
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'prajwalnewpane775@gmail.com');

-- =============================================
-- 4. ADMIN: READ all reviews
-- =============================================

DROP POLICY IF EXISTS reviews_admin_read ON public.reviews;
CREATE POLICY reviews_admin_read
  ON public.reviews
  FOR SELECT
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'prajwalnewpane775@gmail.com');

-- =============================================
-- 5. ADMIN: DELETE users from profiles
-- =============================================

DROP POLICY IF EXISTS profiles_admin_delete ON public.profiles;
CREATE POLICY profiles_admin_delete
  ON public.profiles
  FOR DELETE
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'prajwalnewpane775@gmail.com');

-- =============================================
-- 6. ADMIN: UPDATE other users' profiles (for management)
-- =============================================

DROP POLICY IF EXISTS profiles_admin_update ON public.profiles;
CREATE POLICY profiles_admin_update
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'prajwalnewpane775@gmail.com');

-- Done! You can now see admin panel, messages, newsletter, reviews & WhatsApp clicks.